[package]
name = "helix_rack"
version = "0.1.0"
edition = "2021"
authors = ["Romeu Fonseca <romeu.hcf@gmail.com>"]
license = "MIT"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
magnus = { version = "0.8.2" }
rb-sys = { version = "0.9", features = ["stable-api-compiled-fallback"] }
helixrack-engine = { path = "../../engine" }
tokio = { version = "1", features = ["rt", "net", "io-util", "time", "macros"] }

[build-dependencies]
rb-sys-env = "0.2.2"

[dev-dependencies]
rb-sys-test-helpers = { version = "0.2.2" }
